export const state = {
  theme: localStorage.getItem("vista_theme") || "light",
  seniorMode: JSON.parse(localStorage.getItem("vista_senior") || "false"),
  fontSize: localStorage.getItem("vista_fontsize") || "normal",
  language: localStorage.getItem("vista_language") || "auto",
  voiceReply: JSON.parse(localStorage.getItem("vista_voice_reply") || "false"),
  history: [],
  sidebarCollapsed: JSON.parse(localStorage.getItem("vista_collapsed") || "false"),
  activeHistoryTab: "recent",
  lastBotPayload: null,
  relatedOpen: false,
  modalCallback: null,
  loggedIn: false,
  username: "",
  userEmail: "",
  userPhoto: "",
  userId: "",
  hasConversation: false,
  openMenuId: null,
  confirmationResult: null,
  recognition: null,
  isListening: false,
  isSending: false,
  context: null,
  stopTypingFlag: false,
  typingInterval: null,
  currentSessionId: sessionStorage.getItem("vista_current_session") || null,
  currentMessages: JSON.parse(sessionStorage.getItem("vista_current_messages") || "[]")
};
